#!/bin/bash

# Download The Manifest Tool
curl -s -Lo manifest-tool https://github.com/estesp/manifest-tool/releases/download/v1.0.0/manifest-tool-linux-amd64
chmod +x ./manifest-tool

IMAGE_MISSING="false"

# Configure Branch Variables
if [ "${SOURCE_BRANCH}" = "main" ]
then
  MANIFEST_FILE=manifest.yaml
elif [ "${SOURCE_BRANCH}" = "develop" ]
then
  MANIFEST_FILE=dev-manifest.yaml
fi

# Check If All Images Are Available
echo
for IMAGE_TAG in $(grep "\- image:" ${MANIFEST_FILE} | cut -d":" -f 3)
do
  if ./manifest-tool inspect "${DOCKER_REPO}:${IMAGE_TAG}" 2> /dev/null
  then
    echo "Image ${DOCKER_REPO}:${IMAGE_TAG} Has Been Found."
  else
    echo "Image ${DOCKER_REPO}:${IMAGE_TAG} NOT FOUND!"
    IMAGE_MISSING="true"
  fi
done
echo

# Push Manifest File If All Images Available
if [ "${IMAGE_MISSING}" = "false" ]
then
  ./manifest-tool push from-spec ${MANIFEST_FILE}
fi

# Clean Up
rm -f ./manifest-tool
